#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0

server:
  port: 8181

# Local testing certificates
mutual-tls:
  keystore:
    private-key: "classpath:ssl/dev-proxy-key.pem"
    certificate: "classpath:ssl/dev-proxy-cert.pem"
  truststore:
    certificate: "classpath:ssl/dev-device-service-cert.pem"

config:
  coap:
    coaps-port: 55684
    path: "sng"
    de-duplicator: "NO_DEDUPLICATOR"
    max-active-peers: 20000
    max-message-size: 1024
    max-peer-inactivity-period: "24h"
    max-resource-body-size: 8192
    preferred-block-size: 1024

  http:
    url: "https://localhost:9000"
    connection-timeout: "5000ms"

  udp:
    udp-receive-buffer-size: 8192
    udp-send-buffer-size: 8192
    health-status-interval: "60s"

logging:
  level:
    org.gxf.standalonenotifyinggateway.coaphttpproxy: debug
